# INFINITY SECURITY CONFIGURATION

# Code Execution Security
execution:
  enable_sandbox: true
  allowed_imports:
    - "math"
    - "random"
    - "json"
    - "re"
    - "collections"
    - "itertools"
    - "functools"
  
  forbidden_imports:
    - "os"
    - "sys"
    - "subprocess"
    - "socket"
    - "urllib"
    - "requests"
    - "pickle"
    - "__builtin__"
    - "__builtins__"

  forbidden_functions:
    - "exec"
    - "eval"
    - "compile"
    - "open"
    - "input"
    - "__import__"

# Content Filtering
content_filter:
  enable: true
  dangerous_keywords:
    - "takeover"
    - "control"
    - "dominate"
    - "outsmart"
    - "superintelligent"
    - "override"
    - "bypass"
    - "hack"
    - "exploit"

# Monitoring and Alerts
monitoring:
  enable_alerts: true
  alert_threshold: 3
  log_all_attempts: true
  human_review_required: true
